//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Core.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Specializations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Specializations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePrzychodnia.Core.Translations.Specializations", typeof(Specializations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anestezjologia.
        /// </summary>
        public static string Anesthesiology {
            get {
                return ResourceManager.GetString("Anesthesiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kardiologia.
        /// </summary>
        public static string Cardiology {
            get {
                return ResourceManager.GetString("Cardiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dermatologia.
        /// </summary>
        public static string Dermatology {
            get {
                return ResourceManager.GetString("Dermatology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ginekologia.
        /// </summary>
        public static string Gynecology {
            get {
                return ResourceManager.GetString("Gynecology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internista.
        /// </summary>
        public static string Internist {
            get {
                return ResourceManager.GetString("Internist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neurologia.
        /// </summary>
        public static string Neurology {
            get {
                return ResourceManager.GetString("Neurology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onkologia.
        /// </summary>
        public static string Oncology {
            get {
                return ResourceManager.GetString("Oncology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortopedia.
        /// </summary>
        public static string Orthoapedy {
            get {
                return ResourceManager.GetString("Orthoapedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pediatria.
        /// </summary>
        public static string Pediatrics {
            get {
                return ResourceManager.GetString("Pediatrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychiatria.
        /// </summary>
        public static string Psychiatry {
            get {
                return ResourceManager.GetString("Psychiatry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiologia.
        /// </summary>
        public static string Radiology {
            get {
                return ResourceManager.GetString("Radiology", resourceCulture);
            }
        }
    }
}
